letsencrypt:
  image: fxa-letsencrypt
  net: "host"
  volumes_from:
  -  proxy-config
  ports:
  - "80:80"
  - "443:443"

content:
  image: fxa-content-server
  net: "host"
  expose:
  - "3030"
#  links:
#  - fxa-auth-server
#  - fxa-oauth-server
#  - fxa-profile-server

# fxa-auth-server:
#   image: fxa-auth-server
#   ports:
#   - "9010:9011"
#   links:
#   - fxa-auth-db-mysql
#   - fxa-auth-mailer
#   - browserid-verifier
# 
# fxa-auth-db-mysql:
#   image: fxa-auth-db-mysql
# 
# fxa-auth-mailer:
#   image: fxa-auth-mailer
# 
# browserid-verifier:
#   image: browserid-verifier
# 
# fxa-oauth-server:
#   image: fxa-oauth-server
#   links:
#   - tokenserver
# 
# fxa-profile-server:
#   image: fxa-profile-server
#   links:
#   - tokenserver
# 
# tokenserver:
#   image: tokenserver
# 
# syncserver:
#   image: syncserver
# 
# findmydevice:
#   image: findmydevice
